version: '3'

services:
  dmap_local_rds:
    container_name: dmap_local_rds 
    image: postgres:15.4
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

  dmap_import:
    container_name: dmap_import
    env_file: .env
    build:
      context: .
    depends_on:
      - dmap_local_rds 
    working_dir: /dmap_import 
    command: ["poetry", "run", "start"]
