CUBIC_ODS_TABLES = [
    # WA160
    "EDW.DATE_DIMENSION",
    "EDW.FARE_PROD_USERS_LIST_DIMENSION",
    "EDW.FARE_PRODUCT_DIMENSION",
    "EDW.MEDIA_TYPE_DIMENSION",
    "EDW.OPERATOR_DIMENSION",
    "EDW.RIDE_TYPE_DIMENSION",
    "EDW.ROUTE_DIMENSION",
    "EDW.STOP_POINT_DIMENSION",
    "EDW.TRANSIT_ACCOUNT_DIMENSION",
    "EDW.TXN_STATUS_DIMENSION",
    "EDW.CARD_DIMENSION",
    "EDW.DEVICE_DIMENSION",
    "EDW.USE_TRANSACTION",
    # COMP B
    "EDW.TXN_CHANNEL_MAP",
    "EDW.CCH_AFC_TRANSACTION",
    "EDW.PATRON_TRIP",
    "EDW.TRIP_PAYMENT",
    "EDW.SALE_TRANSACTION",
    "EDW.PAYMENT_TYPE_DIMENSION",
    "EDW.TRANSACTION_HISTORY",
    "EDW.FARE_REVENUE_REPORT_SCHEDULE",  # addendum support
    # FMIS
    "EDW.FNP_GENERAL_JRNL_ACCOUNT_ENTRY",
    "EDW.PAYMENT_SUMMARY",
    # KPI
    "EDW.DEVICE_LAST_STATE",
    "EDW.DEVICE_EVENT",
    "EDW.EVENT_TYPE_DIMENSION",
    "EDW.ABP_TAP",
    "EDW.KPI_MONTHLY_SLDC",
    "EDW.KPI_SUMMARY_BY_DAY",
    # WC231
    # "EDW.CCH_CATEGORY", # cubic not sending
    "EDW.BUSINESS_ENTITY_DIMENSION",
    # "EDW.DISTRIBUTOR_DIMENSION", # no data
    "EDW.SALE_TYPE_DIMENSION",
    # "EDW.CCH_REPROCESS_ACTION", # cubic not sending
    "EDW.CREDIT_CARD_TYPE_DIMENSION",
    # "EDW.TRANSACTION_ORIGIN_DIMENSION", # cubic not sending
    # "EDW.CCH_CATEGORIZE_RULE", # cubic not sending
    # "EDW.CCH_TRANSACTION_TYPE", # cubic not sending
    # "EDW.ACTIVITY_TYPE_DIMENSION", # cubic not sending
    "EDW.RIDER_CLASS_DIMENSION",
    # "EDW.PURSE_TYPE_DIMENSION", # cubic not sending
    # "EDW.DISTRIBUTOR_ORDER", # no data
]
