CUBIC_ODS_TABLES = [
    # wa160
    "EDW.DATE_DIMENSION",
    "EDW.FARE_PROD_USERS_LIST_DIMENSION",
    "EDW.FARE_PRODUCT_DIMENSION",
    "EDW.MEDIA_TYPE_DIMENSION",
    "EDW.OPERATOR_DIMENSION",
    "EDW.RIDE_TYPE_DIMENSION",
    "EDW.ROUTE_DIMENSION",
    "EDW.STOP_POINT_DIMENSION",
    "EDW.TRANSIT_ACCOUNT_DIMENSION",
    "EDW.TXN_STATUS_DIMENSION",
    "EDW.CARD_DIMENSION",
    "EDW.DEVICE_DIMENSION",
    "EDW.USE_TRANSACTION",
    # comp b
    "EDW.TXN_CHANNEL_MAP",
    "EDW.CCH_AFC_TRANSACTION",
    "EDW.PATRON_TRIP",
    "EDW.TRIP_PAYMENT",
    "EDW.SALE_TRANSACTION",
    "EDW.PAYMENT_TYPE_DIMENSION",
    "EDW.TRANSACTION_HISTORY",
    # fmis
    "EDW.FNP_GENERAL_JRNL_ACCOUNT_ENTRY",
]
