import sqlalchemy as sa
from dmap_import.schemas import SqlBase


class DeviceEvents(SqlBase):
    """Table for A.3.4 DEVICE EVENTS"""

    # pylint: disable=too-few-public-methods

    __tablename__ = "device_event"

    pk_id = sa.Column(sa.Integer, primary_key=True)
    dataset_id = sa.Column(sa.String(), nullable=True, index=True)
    id = sa.Column(sa.String(), nullable=True)
    inserted_dtm = sa.Column(sa.DateTime, nullable=True)
    updated_dtm = sa.Column(sa.DateTime, nullable=True)
    depersonalized_dtm = sa.Column(sa.DateTime, nullable=True)
    updated_flag = sa.Column(sa.Integer, nullable=True)
    event_type_id = sa.Column(sa.BigInteger, nullable=True)
    event_source = sa.Column(sa.String(), nullable=True)
    event_type_name = sa.Column(sa.String(), nullable=True)
    event_type_desc = sa.Column(sa.String(), nullable=True)
    severity = sa.Column(sa.Integer, nullable=True)
    period_name = sa.Column(sa.String(), nullable=True)
    period_desc = sa.Column(sa.String(), nullable=True)
    device_name = sa.Column(sa.String(), nullable=True)
    device_desc = sa.Column(sa.String(), nullable=True)
    device_status_id = sa.Column(sa.Integer, nullable=True)
    operator_name = sa.Column(sa.String(), nullable=True)
    operator_desc = sa.Column(sa.String(), nullable=True)
    facility_name = sa.Column(sa.String(), nullable=True)
    facility_desc = sa.Column(sa.String(), nullable=True)
    business_entity_id = sa.Column(sa.String(), nullable=True)
    business_entity_name = sa.Column(sa.String(), nullable=True)
    business_entity_desc = sa.Column(sa.String(), nullable=True)
    business_entity_status_id = sa.Column(sa.String(), nullable=True)
    bus_desc = sa.Column(sa.String(), nullable=True)
    bus_status_id = sa.Column(sa.Integer, nullable=True)
    bus_status_name = sa.Column(sa.String(), nullable=True)
    bus_status_desc = sa.Column(sa.String(), nullable=True)
    bus_type_id = sa.Column(sa.String(), nullable=True)
    bus_type_name = sa.Column(sa.String(), nullable=True)
    bus_type_desc = sa.Column(sa.String(), nullable=True)
    device_type_id = sa.Column(sa.BigInteger, nullable=True)
    device_type_name = sa.Column(sa.String(), nullable=True)
    device_type_desc = sa.Column(sa.String(), nullable=True)
    transit_mode_id = sa.Column(sa.Integer, nullable=True)
    transit_mode_name = sa.Column(sa.String(), nullable=True)
    transit_mode_desc = sa.Column(sa.String(), nullable=True)
    array_position = sa.Column(sa.Integer, nullable=True)
    event_day = sa.Column(sa.DateTime, nullable=True)
    posting_day = sa.Column(sa.DateTime, nullable=True)
    clear_day = sa.Column(sa.DateTime, nullable=True)
    automatic_clear_flag = sa.Column(sa.Integer, nullable=True)
    bus_id = sa.Column(sa.Integer, nullable=True)
    clear_dtm = sa.Column(sa.DateTime, nullable=True)
    clear_message_id = sa.Column(sa.BigInteger, nullable=True)
    clear_event_state_type_id = sa.Column(sa.Integer, nullable=True)
    clear_event_state_type_name = sa.Column(sa.String(), nullable=True)
    component_position = sa.Column(sa.Integer, nullable=True)
    component_serial_nbr = sa.Column(sa.BigInteger, nullable=True)
    component_type_id = sa.Column(sa.Integer, nullable=True)
    component_type_name = sa.Column(sa.String(), nullable=True)
    device_id = sa.Column(sa.String(), nullable=True)
    device_position = sa.Column(sa.Integer, nullable=True)
    device_transaction_id = sa.Column(sa.String(), nullable=True)
    event_dtm = sa.Column(sa.DateTime, nullable=True)
    event_state_type_id = sa.Column(sa.Integer, nullable=True)
    event_state_type_name = sa.Column(sa.String(), nullable=True)
    event_status_path_id = sa.Column(sa.String(), nullable=True)
    event_status_path_name = sa.Column(sa.String(), nullable=True)
    extended_data_short = sa.Column(sa.String(), nullable=True)
    extended_data_long = sa.Column(sa.String(), nullable=True)
    extended_data_string = sa.Column(sa.String(), nullable=True)
    external_device_id = sa.Column(sa.String(), nullable=True)
    facility_id = sa.Column(sa.Integer, nullable=True)
    matched_flag = sa.Column(sa.Integer, nullable=True)
    message_id = sa.Column(sa.BigInteger, nullable=True)
    operator_id = sa.Column(sa.Integer, nullable=True)
    route_number = sa.Column(sa.Integer, nullable=True)
    block_number = sa.Column(sa.String(), nullable=True)
    latitude = sa.Column(sa.Float, nullable=True)
    longitude = sa.Column(sa.Float, nullable=True)
    event_reason_code_id = sa.Column(sa.Integer, nullable=True)
    _exported_dtm = sa.Column(sa.DateTime, nullable=True)
