name: Deploy to Prod Environment

on:
  # deploy when version tags are pushed
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+	
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_URI }}
          env-name: prod 
